import type { Metadata } from 'next';
//import Providers from '@/components/layouts/Providers';

export const metadata: Metadata = {
  title: 'KasirLite',
  description: 'Generated by create next app',
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <div>test ini login layout</div>
      <main>{children}</main>
    </div>
  );
}
